version: "3.0"

services:
    db: 
        image: postgres
        container_name: rentx_db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=rentx
        volumes: 
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rentx_api
        ports: 
            - 3001:3001
        volumes: 
            - .:/usr/app
        links: 
            - db
        depends_on:
            - db
volumes: 
    pgdata: